AWSTemplateFormatVersion: 2010-09-09
Description: Deploy cloudwatch event rules for emr
Parameters:
  SNSTopicName:
    Description: Please enter sns topic name of fizz stack alerts
    Type: String
Resources:
  EMREvent:
    Type: AWS::Events::Rule
    Description: EMR state change rule
    Properties: 
      Description: String
      EventPattern: {
      "source": [
        "aws.emr"
      ],
      "detail-type": [
        "EMR Auto Scaling Policy State Change",
        "EMR Step Status Change",
        "EMR Cluster State Change",
        "EMR Instance Group State Change",
        "EMR Instance Fleet State Change",
        "EMR Instance Group Status Notification"
      ]
    }
      Name: !Sub ${AWS::StackName}-fizz-emr
      State: ENABLED
      Targets: 
        - Arn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicName}
          Id: !Sub ${AWS::StackName}-fizz-emr-alert