NAMESPACE=$1
HBASE_CLI="hbase"

# chat group
NS_CHAT_GROUP="chat_group_$NAMESPACE"
TABLE_GROUP="tbl_group"
GROUP_CF_CONTENT="c"
GROUP_CF_EVENTS="es"

TABLE_USER_GROUP="tbl_user_group"
USER_GROUP_CF_CONTENT="c"

exec "$HBASE_CLI" shell <<EOF
create_namespace '$NS_CHAT_GROUP'

create '$NS_CHAT_GROUP:$TABLE_GROUP', {NAME => '$GROUP_CF_CONTENT', VERSIONS => 1}, {NAME => '$GROUP_CF_EVENTS', VERSIONS => 1, REPLICATION_SCOPE => 1}
create '$NS_CHAT_GROUP:$TABLE_USER_GROUP', {NAME => '$USER_GROUP_CF_CONTENT', VERSIONS => 1}
EOF
