{
 "title": "Emqx metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory/15s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_total_metric_guage", "legendFormat": "{{instance}}:total_mem" },
    { "expr": "node_memory_used_metric_guage", "legendFormat": "{{instance}}:used_mem" }
   ]
  },
  {
   "title": "connections/node/15s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_connections_metric_guage", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "connections/node/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_connections_metric_guage", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "connections/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_connections_metric_guage)",
     "legendFormat": "total connections"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "%EMQX_CLUSER_NAME%" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "CPU/node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aws_ec2_cpuutilization_maximum", "legendFormat": "{{instance_id}}:cpu" }
   ]
  },
  {
   "title": "total publish",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_messages_publish_metric_guage)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "publish/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_messages_publish_metric_guage) - sum(node_messages_publish_metric_guage offset 1m)",
     "legendFormat": "pub/min"
    }
   ]
  },
  {
   "title": "publish/node/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_messages_publish_metric_guage) - (node_messages_publish_metric_guage offset 1m)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total messages sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_messages_qos0_sent_metric_guage)",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "messages sent/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_messages_qos0_sent_metric_guage) - sum(node_messages_qos0_sent_metric_guage offset 1m)",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "messages sent/node/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_messages_qos0_sent_metric_guage) - (node_messages_qos0_sent_metric_guage offset 1m)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_node_status_metric_guage", "legendFormat": "{{instance}}:status" }
   ]
  },
  {
   "title": "processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_process_available_metric_guage",
     "legendFormat": "{{instance}}:process_available"
    },
    { "expr": "node_process_used_metric_guage", "legendFormat": "{{instance}}:process_used" }
   ]
  }
 ]
}