{
 "title": "Fizz Detailed View",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Emqx metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_total_metric_guage", "legendFormat": "{{instance}}:total_mem" },
    { "expr": "node_memory_used_metric_guage", "legendFormat": "{{instance}}:used_mem" }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_connections_metric_guage", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_process_available_metric_guage",
     "legendFormat": "{{instance}}:process_available"
    },
    { "expr": "node_process_used_metric_guage", "legendFormat": "{{instance}}:process_used" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "%EMQX_CLUSER_NAME%" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "api-gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "fizz-api-gateway-blue Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "EnvironmentName": "%API_GATEWAY_BLUE_ENVIRONMENT_NAME%"
     },
     "metricName": "EnvironmentHealth",
     "namespace": "AWS/ElasticBeanstalk",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-blue Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "InstanceId": "*",
      "env": "%API_GATEWAY_BLUE_ENVIRONMENT_NAME%"
     },
     "metricName": "mem_used",
     "namespace": "Fizz/Gateway",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-blue Latency /s (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_BLUE_LOAD_BALANCER_NAME%"
     },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "api-gateway-blue Cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%API_GATEWAY_BLUE_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-blue host count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_BLUE_LOAD_BALANCER_NAME%"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-blue ELB 5xx errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_BLUE_LOAD_BALANCER_NAME%"
     },
     "metricName": "HTTPCode_ELB_5XX",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Sum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "fizz-api-gateway-green Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "EnvironmentName": "%API_GATEWAY_GREEN_ENVIRONMENT_NAME%"
     },
     "metricName": "EnvironmentHealth",
     "namespace": "AWS/ElasticBeanstalk",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-blue RequestCount(sum)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_BLUE_LOAD_BALANCER_NAME%"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Sum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "InstanceId": "%API_GATEWAY_GREEN_ENVIRONMENT_NAME%"
     },
     "metricName": "MemoryUtilization",
     "namespace": "System/Linux",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green Cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%API_GATEWAY_GREEN_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green host count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_GREEN_LOAD_BALANCER_NAME%"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-blue system&instance check failure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%API_GATEWAY_BLUE_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%API_GATEWAY_BLUE_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green system&instance check failure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%API_GATEWAY_GREEN_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%API_GATEWAY_GREEN_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green ELB 5xx errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_GREEN_LOAD_BALANCER_NAME%"
     },
     "metricName": "HTTPCode_ELB_5XX",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Sum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green RequestCount(sum)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_GREEN_LOAD_BALANCER_NAME%"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Sum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "api-gateway-green Latency(max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "LoadBalancerName": "%API_GATEWAY_GREEN_LOAD_BALANCER_NAME%"
     },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  { "title": "ElasticSearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "JVMMemoryPressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "Storage Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Minimum" ],
     "transform": "none"
    },
    {
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "ClusterUsedSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Cpu utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "DeletedDocuments",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "DeletedDocuments",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "SearchableDocuments",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "WriteLatency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "WriteLatency",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "ReadLatency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "ReadLatency",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "Read/WriteIOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/ES",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    },
    {
     "dimensions": { "ClientId": "%AWS_ACCOUNT_ID%", "DomainName": "%ELASTIC_SEARCH_DOMAIN_NAME%" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "Fizz NoEviction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Cpu utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "001",
     "dimensions": { "CacheClusterId": "%REDIS_CLUSTER_NODE_NAME%" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "001",
     "dimensions": { "CacheClusterId": "%REDIS_CLUSTER_NODE_NAME%" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "precision": "default",
     "region": "default",
     "statistics": [ "Average" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "Cache Hits / Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "001_CacheHits",
     "dimensions": { "CacheClusterId": "%REDIS_CLUSTER_NODE_NAME%" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "precision": "default",
     "region": "default",
     "statistics": [ "Average" ],
     "transform": "none"
    },
    {
     "alias": "002_CacheMisses",
     "dimensions": { "CacheClusterId": "%REDIS_CLUSTER_NODE_NAME%" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "keycloak", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "keycloak-green Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%KEYCLOAK_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "keycloak-green latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "LoadBalancerName": "%KEYCLOAK_LOAD_BALANCER_NAME%" },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "keycloak-green RequestCount(sum)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "LoadBalancerName": "%KEYCLOAK_LOAD_BALANCER_NAME%" },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "precision": "default",
     "region": "default",
     "statistics": [ "Sum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "keycloak-green Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "EnvironmentName": "%KEYCLOAK_ENVIRONMENT_NAME%" },
     "metricName": "EnvironmentHealth",
     "namespace": "AWS/ElasticBeanstalk",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "keycloak-green Memeory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": { "ClusterName": "%KEYCLOAK_LOAD_BALANCER_NAME%" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    }
   ]
  },
  {
   "title": "keycloak-green Network in/out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": {
      "AutoScalingGroupName": "%KEYCLOAK_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "precision": "default",
     "region": "default",
     "statistics": [ "Maximum" ],
     "transform": "none"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "%KEYCLOAK_AUTO_SCALING_GROUP_NAME%"
     },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "MSK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CPU (User)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "CpuUser",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "RootDiskUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "RootDiskUsed",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "MemoryFree",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "MemoryFree",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  { "title": "Hbase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Host Master Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "cpu_user",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_system",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "cpu_system",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_nice",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "cpu_nice",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Host RS Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "cpu_user",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_system",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "cpu_system",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_nice",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "cpu_nice",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase Master Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "hbase",
     "metric": "load_one",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HDFS Blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Blocks Count",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.BlocksTotal",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HDFS Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Capacity Total",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.CapacityTotal",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Capacity Remaining",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.CapacityRemaining",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Capacity Used (DFS)",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.CapacityUsed",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Capacity Used (Non-DFS)",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.CapacityUsedNonDFS",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase Master GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "GC Pause",
     "app": "hbase",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "none",
     "alias": "GC Count",
     "app": "hbase",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "HBase RS GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "GC Pause",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "none",
     "alias": "GC Count",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Hbase Proxy Heartbeat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "hbase-kafka-proxy",
     "metric": "heartbeat",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Compactions & Flushes Queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Compaction Queue",
     "app": "hbase",
     "metric": "regionserver.Server.compactionQueueLength",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Flush Queue",
     "app": "hbase",
     "metric": "regionserver.Server.flushQueueLength",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Region Server Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Read Requests",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.readRequestCount",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "max",
     "alias": "Write Requests",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.writeRequestCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  }
 ]
}