{
 "title": "Ambari Hbase Cluster (Live)",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "HBase Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Master Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Total",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "mem_total",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "mem_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Host RS Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Total",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "mem_total",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "mem_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase Master Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max Heap",
     "app": "hbase",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used Heap",
     "app": "hbase",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase RS Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max Heap",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used Heap",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Commited Heap",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapCommittedM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Commited Non Heap",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemNonHeapCommittedM",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase Caches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Memstore Size",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.memStoreSize",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "BlockCache Size",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.blockCacheSize",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "BlockCache Free Size",
     "app": "hbase",
     "metric": "regionserver.Server.blockCacheFreeSize",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase Caching Ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "BlockCache Hit Ratio",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.blockCacheCountHitPercent",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Block Cache Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "block cache count",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.blockCacheCount",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase RS GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "GC Pause",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "none",
     "alias": "GC Count",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "NameNode Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max Heap",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used Heap",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "DataNode Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max Heap",
     "app": "datanode",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used Heap",
     "app": "datanode",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Host RS Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "cpu_user",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_system",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "cpu_system",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_nice",
     "app": "HOST",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "cpu_nice",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Host Master Cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "cpu_user",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_system",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "cpu_system",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "cpu_nice",
     "app": "HOST",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "cpu_nice",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HBase Master GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "GC Pause",
     "app": "hbase",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "none",
     "alias": "GC Count",
     "app": "hbase",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "HBase Master Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "hbase",
     "metric": "load_one",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  { "title": "HBase Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HDFS Blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Blocks Count",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "dfs.FSNamesystem.BlocksTotal",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HDFS Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Capacity Total",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "dfs.FSNamesystem.CapacityTotal",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Capacity Remaining",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "dfs.FSNamesystem.CapacityRemaining",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Capacity Used (DFS)",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "dfs.FSNamesystem.CapacityUsed",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Capacity Used (Non-DFS)",
     "app": "namenode",
     "hosts": "%HBASE_MASTER_PRIVATE_DNS%",
     "metric": "dfs.FSNamesystem.CapacityUsedNonDFS",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Region Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Average Region Size",
     "app": "hbase",
     "metric": "regionserver.Server.averageRegionSize",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Store File Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Count",
     "app": "hbase",
     "metric": "regionserver.Server.storeFileCount",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Store File Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Store File Size",
     "app": "hbase",
     "metric": "regionserver.Server.storeFileSize",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Store File Index Size",
     "app": "hbase",
     "metric": "regionserver.Server.storeFileIndexSize",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Store File Age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Average Age",
     "app": "hbase",
     "metric": "regionserver.Server.avgStoreFileAge",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Max Age",
     "app": "hbase",
     "metric": "regionserver.Server.maxStoreFileAge",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Min Age",
     "app": "hbase",
     "metric": "regionserver.Server.minStoreFileAge",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  { "title": "House Keeping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Compactions & Flushes Queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Compaction Queue",
     "app": "hbase",
     "metric": "regionserver.Server.compactionQueueLength",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Flush Queue",
     "app": "hbase",
     "metric": "regionserver.Server.flushQueueLength",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Compaction & Flush Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Compaction Time",
     "app": "hbase",
     "metric": "regionserver.Server.CompactionTime_mean",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Flush Time",
     "app": "hbase",
     "metric": "regionserver.Server.FlushTime_mean",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  { "title": "Hbase Kafka Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Hbase Proxy Heartbeat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "hbase-kafka-proxy",
     "metric": "heartbeat",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Hbase Proxy Live Hosts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "hbase-kafka-proxy",
     "metric": "live_hosts",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Hbase Proxy Records Processed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "hbase-kafka-proxy",
     "metric": "records-processed",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Region Server Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Read Requests",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.readRequestCount",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "max",
     "alias": "Write Requests",
     "app": "hbase",
     "hosts": "%HBASE_SLAVE_PRIVATE_DNS%",
     "metric": "regionserver.Server.writeRequestCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  }
 ]
}