{
 "title": "MSK",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU (User)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "CpuUser",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "CPU (System)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "CpuSystem",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "KafkaAppLogsDiskUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "KafkaAppLogsDiskUsed",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "KafkaDataLogsDiskUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "KafkaDataLogsDiskUsed",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "RootDiskUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "RootDiskUsed",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ZooKeeperSessionState",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "ZooKeeperSessionState",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "MemoryFree",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "MemoryFree",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "MemoryUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "MemoryUsed",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ZooKeeperRequestLatencyMsMean",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "ZooKeeperRequestLatencyMsMean",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "PacketsReceivedByBroker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "NetworkRxPackets",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "PacketsTransmittedByBroker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "NetworkTxPackets",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "NetworkRxDropped/NetworkRxErrors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "NumberOfDroppedReceivePackages",
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "NetworkRxDropped",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "NumberOfNetworkReceiveErrorsForTheBroker",
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "NetworkRxErrors",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NetworkTxDropped/NetworkTxErrors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "NumberOfDroppedTransmitPackages",
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "NetworkTxDropped",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "NumberOfNetworkTransmitErrorsForTheBroker",
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "NetworkTxErrors",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "GlobalPartitionCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "GlobalTopicCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "GlobalTopicCount",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "OfflinePartitionsCount",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "%MSK_CLUSTER_NAME%" },
     "metricName": "ActiveControllerCount",
     "namespace": "AWS/Kafka",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}